pekko.http.server.max-connections = 1500
pekko.http.server.preview.enable-http2 = on
pekko.http.server.http2.min-collect-strict-entity-size = 1

pekko.actor.default-dispatcher.executor = "affinity-pool-executor"
pekko.actor.default-dispatcher.affinity-pool-executor.parallelism-factor = 1.0
pekko.actor.default-dispatcher.affinity-pool-executor.idle-cpu-level = 5
pekko.actor.default-dispatcher.affinity-pool-executor.task-queue-size = 512
