name: ShellCheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    env:
      VSN: v0.8.0
    steps:
    - uses: actions/checkout@v2
    - run: |
        wget -qO- "https://github.com/koalaman/shellcheck/releases/download/$VSN/shellcheck-$VSN.linux.x86_64.tar.xz" | tar -xJv
        ./shellcheck-$VSN/shellcheck --version
    - run: ./shellcheck-$VSN/shellcheck ./generate_ci.sh # TODO: $(find . -type f -name '*.sh')
